### ISSUE TITLE
Bug?

### ISSUE THREAD

**Issue by mapeveri** [sleeping-owl/admin#259]
I have this columns:

      Column::string('id', 'ID');
      Column::string('id_usuario.username', 'Usuario');
      Column::string('id_cliente.nm_cliente', 'Cliente');
      Column::string('id_proyecto.nm_proyecto', 'Proyecto');

But the column id i had to add because otherwise it give me error. The error: "Column not found: 1054 Unknown column 'id_usuario.username' ". If added the column id works well. 
It can be a bug or error in my code?

Thanks!

**Comment by macedodebrito** [comment]
i dont use V3 but, seems you are using different tables.

you need to setup that first.

**Comment by mapeveri** [comment]
@macedodebrito hi, thanks for answering. I use last version.
Problem with tables i don't believe, because the code of top works well. The problem is if remove the column "ID". In that case if I get error tables.

**Comment by macedodebrito** [comment]
hello again @mapeveri :)

if you use ID col, the other 3 grab the proper info? hum.. wierd..

**Comment by mapeveri** [comment]
@macedodebrito exactly. Very weird :)

**Comment by s6carlo** [comment]
I has something similar: the cause seems to be related to having the first column from a different table. 
Try to add a column from the table of the model (not necessarily id) and it works.
In my case I use a Datatables async display and I think this "bug" is due to the fact that column from foreign tables are not orderable.

**Comment by mapeveri** [comment]
@s6carlo thanks!!
