### ISSUE TITLE
FormItem::view('admin.article.view')

### ISSUE THREAD

**Issue by eugenem** [sleeping-owl/admin#76]
How do I get currently edited item model in this view? I don't see that you're passing it to the view here:
https://github.com/sleeping-owl/admin/blob/master/src/SleepingOwl/Admin/Models/Form/FormItem/View.php

And how do I inject code into the saving procedure afterwards?

Let's say I have form for order and want to add that sub-view for order lines. Is this feasible?

**Comment by sleeping-owl** [comment]
You can't write code for saving procedure in the form item because this package saves entity by using eloquent `fill()` method with all request data.

So you can add `<input name="my_field">` to the form, add `my_field` to your model's `$fillable` attribute and parse it with:
```php
public function setMyFieldAttribute($value)
{
  $this->attributes['my_field'] = some_func($value);
}
```
in your model.

----

In the new version of this package (in the development branch now, there is no backward compatibility) this logic was changed. Every form item perform saving procedure by itself. You can use `custom` form item (https://github.com/sleeping-owl/admin/blob/development/src/SleepingOwl/Admin/FormItems/Custom.php) and write your saving procedure in `callback` closure.
